<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Command line test"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="0.003">
    <properties></properties>

            <testcase
                name="testMapDataProvider"
                time="0.000"
                classname="testData.data01.DataProviderTest">

            <failure type="org.testng.TestNGException" message="
Method public void testData.data01.DataProviderTest.testMapDataProvider(java.util.HashMap) requires a @DataProvider named : mapDataProvider1">
                <![CDATA[org.testng.TestNGException: 
Method public void testData.data01.DataProviderTest.testMapDataProvider(java.util.HashMap) requires a @DataProvider named : mapDataProvider1
                org.testng.internal.Parameters.findDataProvider(Parameters.java:559)org.testng.internal.Parameters.handleParameters(Parameters.java:772)org.testng.internal.Parameters.handleParameters(Parameters.java:740)org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1257)org.testng.TestRunner.privateRun(TestRunner.java:764)org.testng.TestRunner.run(TestRunner.java:585)org.testng.SuiteRunner.runTest(SuiteRunner.java:384)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)org.testng.SuiteRunner.run(SuiteRunner.java:286)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)org.testng.TestNG.runSuitesLocally(TestNG.java:1140)org.testng.TestNG.runSuites(TestNG.java:1069)org.testng.TestNG.run(TestNG.java:1037)org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </failure>
    </testcase>


            <testcase
                name="testArrayDataProvider"
                time="0.000"
                classname="testData.data01.DataProviderTest">
            </testcase>
            <testcase
                name="testArrayDataProvider"
                time="0.001"
                classname="testData.data01.DataProviderTest">
            </testcase>
            <testcase
                name="testArrayDataProvider"
                time="0.000"
                classname="testData.data01.DataProviderTest">
            </testcase>
            <testcase
                name="testArrayDataProvider"
                time="0.002"
                classname="testData.data01.DataProviderTest">
            </testcase>
</testsuite>
